"use client";

import type { Narrative } from "@/lib/types";

export default function NarrativePanel({
  narrative,
}: {
  narrative: Narrative;
}) {
  return (
    <section className="card accent">
      <h2>Narrative Synthesis</h2>
      <p className="headline">{narrative.headline}</p>
      <p className="narrative-body">{narrative.narrative}</p>
      <div className="insight">
        <strong>What to do with it</strong>
        {narrative.actionable_insight}
      </div>
      {/* Stating which engine wrote this is deliberate: a deterministic
          fallback sentence and a model-written one carry different weight,
          and the reader is entitled to know which they are looking at. */}
      <div className="gen-mode">
        {narrative.generation_mode === "llm"
          ? `generated by ${narrative.model ?? "model"}`
          : "deterministic summary — no Anthropic key configured, so this was assembled from the measured signals alone"}
      </div>
    </section>
  );
}
